### PR TITLE
Fix colors not working when calling borders.py

### PR DESCRIPTION
**Pull request by faissaloux**
In this PR I have fixed colors not working when calling `borders.py` directly inside `if __name__ == "__main__":` block.

### CODE REVIEW

**Comment by scalvaruso** [comment]
I'm not really familiar with "colorama", and I didn't actually experience any problem with colours before or after adding it.
"borders.py" it's not really meant to be called directly, so I'm not sure it would be a meaningful change.
Can you be more specific on the issues you encountered. Cheers

**Comment by faissaloux** [comment]
"'borders.py' it's not really meant to be called directly"
yeah I wanted to remove the `if __name__ == "__main__":` block for this reason, but I wasn't sure about your use of it!

If not supposed to be called directly I'll remove that block and the `main()` method since it's only called on that block and move 'colorama' call to __init__ file as I made it on last PR #1, and that would be perfect.

`colorama` is a library that make sure those ANSI chars works perfectly on windows. Are you using it on Windows? because Unix systems are not concerned about this issue.

**Comment by faissaloux** [comment]
@scalvaruso what do you think?

**Comment by scalvaruso** [comment]
Hi, sorry I was away.
I would just leave colorama in the __init__ file as it is to solve compatibility issues with windows, but I need to keep the main() function and if block for a private project connected to border.
Cheers

**Comment by faissaloux** [comment]
If we leave `colorama` in `__init__` it wouldn't work inside the `if __name__ == "__main__":` block.

**Comment by scalvaruso** [comment]
As specified in the usage you have to import frame, so it doesn't really matter if colorama works or not in main().

**Comment by faissaloux** [comment]
Ah okay, if it's not important to work in `main()`, I'm closing this PR for now.
Thanks

**Comment by scalvaruso** [comment]
No problem, thank you for your contribution.

**Pull request closed without merging**
